### ISSUE TITLE
Create non-grunt version

### ISSUE THREAD

**Issue by ai** [Sebastian-Fitzner/grunt-data-separator#2]
Your PostCSS plugin is awesome (I always use it as example). But very bad, that it is only for Grunt. We have a lot of Gulp users (and useful [gulp-postcss](https://github.com/w0rm/gulp-postcss)) and my company will use webpack (I plan to develop `postcss-loader`).

Can you release separated npm package with main logic on PostCSS processor?

/cc @Sebastian-Fitzner

**Comment by Grawl** [comment]
Now I trying to move all my post-CSS logic into `grunt-postcss` and also want to separate CSS with `data-separator` but obviously cannot before it becomes pure postCSS plugin. I think about [`postcss-data-packer`](https://github.com/Ser-Gen/postcss-data-packer) but it has much less features.

**Comment by Sebastian-Fitzner** [comment]
I haven't had any time until now, but I really like the idea to publish it as standalone npm package. So I will manage to get some spare time to put something together til sunday next week ...

**Comment by Grawl** [comment]
Cool, will wait for it.

**Comment by ai** [comment]
I think we should better to send PR to [postcss-data-packer](https://github.com/Ser-Gen/postcss-data-packer).

**Comment by Grawl** [comment]
Maybe but `postcss-data-packer` can work only with `/url\(["']?data/g` but `grunt-data-separator` can also separate by property (`background-image` for example), media (search for `/min-resolution: 2dppx/`) and extract styles with parent (extract with `@media` block). It's a killer features here for me. I do two files: `images.css` and `images@2x.css` and load just one of them depending on user' screen.

**Comment by ai** [comment]
@Grawl and we should move this features to `postcss-data-packer`.

**Comment by Grawl** [comment]
@ai awesome if someone can do it.

**Comment by ai** [comment]
@Grawl create a issues there.

**Comment by Sebastian-Fitzner** [comment]
@Grawl on weekend I had some time to write a first version of the new package. In the next few days I am going to have a productive version which you can use ... I let the ticket open til the package is published.

**Comment by Grawl** [comment]
@Sebastian-Fitzner ok I found it https://github.com/Sebastian-Fitzner/postcss-separator will watch it

**Comment by Sebastian-Fitzner** [comment]
First steps are made. A new package is available. Next steps are tests and plugin integration. All new issues should be opened at  https://github.com/Sebastian-Fitzner/postcss-separator.
